### ISSUE TITLE
Push error

### ISSUE THREAD

**Issue by Hasmann** [sutanAE/junior-software-engineer-test#2]
hi, i have forked the repo but i am getting permission denied error, can you give me the permission to push to the your code-repository

**Comment by sutanAE** [comment]
Hi @Hasmann thank you for taking the test.

To clarify, you won't have any Push privileges to this repository. You can, however, create your own repository (by forking or cloning), push your code to **your** repository, and then send us the link to your repo.

Additionally, submitting your code can be done via Pull request if you opt for [git fork workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) (which is not mandatory), as this test is also an open-source project simulation. Please watch this [example video on how to contribute to open source project](https://www.youtube.com/watch?v=CML6vfKjQss).

Alternatively, you can zip your repository, upload it to a drive service and send it to our email.

I hope this helps.

Kind regards,
Sutan
